import { type PokemonGoItem, type PokemonGoItemCategory } from "@/types/pokemon-go";
import completePokemonGoItems from "@/data/pokemon-go-items-complete.json";

function normalize(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
}

const CURATED_POKEMON_GO_ITEMS: PokemonGoItem[] = [
  {
    id: 1,
    slug: "poke-ball",
    name: "Poke Ball",
    category: "balls",
    categoryLabel: "Capture Balls",
    rarity: "Common",
    availability: "Both",
    description: "Base capture ball for regular encounters.",
    inGameEffect: "Standard catch multiplier.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Gyms", "Gifts", "Research", "Shop bundles"],
    bestUseCases: ["Routine catch loops", "Event mass catching"],
    relatedSystems: ["Catch XP", "Candy farming"],
    pvpRelevance: "Indirect via species farming.",
    raidRelevance: "No direct use for premier-ball raid catches.",
    notes: ["Use higher tiers for difficult targets."],
    searchTags: ["capture", "basic", "ball"]
  },
  {
    id: 2,
    slug: "great-ball",
    name: "Great Ball",
    category: "balls",
    categoryLabel: "Capture Balls",
    rarity: "Uncommon",
    availability: "Both",
    description: "Mid-tier ball with stronger catch chance than Poke Ball.",
    inGameEffect: "Improved catch rate over base balls.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Gyms", "Gifts", "Research", "Shop bundles"],
    bestUseCases: ["Harder wild catches", "Save Ultra Balls for priority targets"],
    relatedSystems: ["Event catches", "Incense sessions"],
    pvpRelevance: "Useful for PvP IV hunting volume.",
    raidRelevance: "Indirect only.",
    notes: ["Good efficiency-to-cost balance."],
    searchTags: ["great ball", "capture", "mid tier"]
  },
  {
    id: 3,
    slug: "ultra-ball",
    name: "Ultra Ball",
    category: "balls",
    categoryLabel: "Capture Balls",
    rarity: "Rare",
    availability: "Both",
    description: "High-tier ball for difficult and rare encounters.",
    inGameEffect: "Strong catch multiplier among standard balls.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Gyms", "Gifts", "Research", "Shop bundles"],
    bestUseCases: ["Rare spawn catches", "Daily Adventure Incense encounters"],
    relatedSystems: ["Rare hunt", "Event optimization"],
    pvpRelevance: "High indirect value for scarce meta species.",
    raidRelevance: "Not used in premier-ball capture phase.",
    notes: ["Pair with Golden Razz on risky catches."],
    searchTags: ["ultra ball", "rare catch", "high chance"]
  },
  {
    id: 4,
    slug: "master-ball",
    name: "Master Ball",
    category: "balls",
    categoryLabel: "Capture Balls",
    rarity: "Epic",
    availability: "Event",
    description: "Guaranteed catch item with very limited supply.",
    inGameEffect: "Always captures target if throw connects.",
    stackCap: "Very limited",
    consumable: true,
    acquisition: ["Special research", "Limited distributions"],
    bestUseCases: ["Emergency rare catches with high flee risk"],
    relatedSystems: ["Long-term resource planning"],
    pvpRelevance: "Can secure rare competitive species.",
    raidRelevance: "No direct raid premier-ball interaction.",
    notes: ["Use only when replacement opportunity is low."],
    searchTags: ["master ball", "guaranteed", "limited"]
  },
  {
    id: 5,
    slug: "razz-berry",
    name: "Razz Berry",
    category: "berries",
    categoryLabel: "Berries",
    rarity: "Common",
    availability: "Both",
    description: "Basic berry that boosts catch chance.",
    inGameEffect: "Improves catch probability for next throw.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Gyms", "Gifts", "Research"],
    bestUseCases: ["General catch consistency"],
    relatedSystems: ["Catch flow"],
    pvpRelevance: "Indirect only.",
    raidRelevance: "Usually replaced by Golden Razz in hard catches.",
    notes: ["Baseline berry for everyday sessions."],
    searchTags: ["razz", "berry", "catch"]
  },
  {
    id: 6,
    slug: "pinap-berry",
    name: "Pinap Berry",
    category: "berries",
    categoryLabel: "Berries",
    rarity: "Uncommon",
    availability: "Both",
    description: "Candy-focused berry for progression-heavy catches.",
    inGameEffect: "Increases candy gained on successful catch.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Gyms", "Gifts", "Research"],
    bestUseCases: ["Community Day", "Candy stockpile projects"],
    relatedSystems: ["Candy economy", "Evolution goals"],
    pvpRelevance: "High indirect value for build projects.",
    raidRelevance: "Situational if catch risk is manageable.",
    notes: ["Switch to Golden Razz if catch chance drops."],
    searchTags: ["pinap", "candy", "farm"]
  },
  {
    id: 7,
    slug: "golden-razz-berry",
    name: "Golden Razz Berry",
    category: "berries",
    categoryLabel: "Berries",
    rarity: "Rare",
    availability: "Both",
    description: "Premium berry for high-value difficult catches.",
    inGameEffect: "Strong catch chance increase.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Raid rewards", "Research", "Events"],
    bestUseCases: ["Legendary catches", "Rare incense encounters"],
    relatedSystems: ["Raid capture reliability"],
    pvpRelevance: "Indirect via rare species capture security.",
    raidRelevance: "Top-tier legendary catch support.",
    notes: ["Do not waste on common targets."],
    searchTags: ["golden razz", "legendary", "premium berry"]
  },
  {
    id: 8,
    slug: "potion",
    name: "Potion",
    category: "healing",
    categoryLabel: "Healing",
    rarity: "Common",
    availability: "Both",
    description: "Entry-level HP healing item.",
    inGameEffect: "Restores small HP amount.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Gyms", "Gifts"],
    bestUseCases: ["Light recovery between minor battles"],
    relatedSystems: ["Gym", "Rocket"],
    pvpRelevance: "No direct PvP use.",
    raidRelevance: "Low at higher levels.",
    notes: ["Trim excess stock when bag space is tight."],
    searchTags: ["potion", "heal", "hp"]
  },
  {
    id: 9,
    slug: "hyper-potion",
    name: "Hyper Potion",
    category: "healing",
    categoryLabel: "Healing",
    rarity: "Uncommon",
    availability: "Both",
    description: "Strong healing item for repeated battles.",
    inGameEffect: "Restores large HP amount.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Gyms", "Raids", "Gifts", "Research"],
    bestUseCases: ["Raid chains", "Rocket-heavy sessions"],
    relatedSystems: ["Battle sustain", "Team maintenance"],
    pvpRelevance: "No direct use in league matches.",
    raidRelevance: "High utility for frequent raiders.",
    notes: ["Good value compared with low-tier potions."],
    searchTags: ["hyper potion", "heal", "raids"]
  },
  {
    id: 10,
    slug: "max-revive",
    name: "Max Revive",
    category: "healing",
    categoryLabel: "Healing",
    rarity: "Rare",
    availability: "Both",
    description: "Revives and fully heals fainted Pokemon.",
    inGameEffect: "Fainted Pokemon returns at full HP.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Raids", "Research", "Event rewards"],
    bestUseCases: ["Fast raid relobby recovery", "High-volume battle days"],
    relatedSystems: ["Raid speed", "Battle loop"],
    pvpRelevance: "No direct arena usage.",
    raidRelevance: "Excellent for time-efficient raid sessions.",
    notes: ["Save for heavy battle windows."],
    searchTags: ["max revive", "full recovery", "raid sustain"]
  },
  {
    id: 11,
    slug: "fast-tm",
    name: "Fast TM",
    category: "battle",
    categoryLabel: "Battle Tech",
    rarity: "Uncommon",
    availability: "Both",
    description: "Rerolls fast move on a Pokemon.",
    inGameEffect: "Changes fast attack from move pool.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Raids", "GO Battle League", "Research"],
    bestUseCases: ["Fixing PvP and raid move sets"],
    relatedSystems: ["Build optimization", "Meta adaptation"],
    pvpRelevance: "High.",
    raidRelevance: "High.",
    notes: ["Avoid random spending on wide move pools."],
    searchTags: ["fast tm", "moveset", "battle"]
  },
  {
    id: 12,
    slug: "charged-tm",
    name: "Charged TM",
    category: "battle",
    categoryLabel: "Battle Tech",
    rarity: "Uncommon",
    availability: "Both",
    description: "Rerolls charged move on a Pokemon.",
    inGameEffect: "Changes charged attack from move pool.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Raids", "GO Battle League", "Research"],
    bestUseCases: ["PvP finetuning", "Raid attacker optimization"],
    relatedSystems: ["Roster tuning", "League prep"],
    pvpRelevance: "Very high.",
    raidRelevance: "Very high.",
    notes: ["Plan target moves before spending."],
    searchTags: ["charged tm", "charged move", "battle"]
  },
  {
    id: 13,
    slug: "elite-charged-tm",
    name: "Elite Charged TM",
    category: "battle",
    categoryLabel: "Battle Tech",
    rarity: "Epic",
    availability: "Premium",
    description: "Selects specific charged move including legacy options.",
    inGameEffect: "Direct move selection from eligible list.",
    stackCap: "Limited",
    consumable: true,
    acquisition: ["Premium tracks", "Shop bundles", "Special events"],
    bestUseCases: ["Legacy move unlocks for top meta species"],
    relatedSystems: ["Endgame optimization", "Legacy management"],
    pvpRelevance: "Extremely high for some cores.",
    raidRelevance: "High when best DPS needs legacy move.",
    notes: ["Treat as premium strategic resource."],
    searchTags: ["elite charged tm", "legacy", "premium"]
  },
  {
    id: 14,
    slug: "sinnoh-stone",
    name: "Sinnoh Stone",
    category: "evolution",
    categoryLabel: "Evolution Items",
    rarity: "Rare",
    availability: "Both",
    description: "High-demand evolution item for many species lines.",
    inGameEffect: "Required for multiple cross-gen evolutions.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["GO Battle League", "Research", "Events"],
    bestUseCases: ["Dex progression", "Meta-relevant evolutions"],
    relatedSystems: ["Evolution planning", "Build pipeline"],
    pvpRelevance: "High indirect value.",
    raidRelevance: "Medium.",
    notes: ["Keep a reserve; demand is frequent."],
    searchTags: ["sinnoh stone", "evolution", "cross gen"]
  },
  {
    id: 15,
    slug: "unova-stone",
    name: "Unova Stone",
    category: "evolution",
    categoryLabel: "Evolution Items",
    rarity: "Rare",
    availability: "Both",
    description: "Evolution item for select Unova evolution lines.",
    inGameEffect: "Unlocks specific item-gated evolutions.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Research", "Events", "Milestone rewards"],
    bestUseCases: ["Generation-specific evolution completion"],
    relatedSystems: ["Dex completion", "Event objectives"],
    pvpRelevance: "Medium by species.",
    raidRelevance: "Medium by species.",
    notes: ["Distribution can be uneven across seasons."],
    searchTags: ["unova stone", "evolution item", "gen5"]
  },
  {
    id: 16,
    slug: "raid-pass",
    name: "Raid Pass",
    category: "raid",
    categoryLabel: "Raid Passes",
    rarity: "Rare",
    availability: "Free",
    description: "Daily in-person pass for one local raid entry.",
    inGameEffect: "Grants local raid access.",
    stackCap: "Limited carryover",
    consumable: true,
    acquisition: ["Daily gym spin"],
    bestUseCases: ["Daily legendary/mega participation"],
    relatedSystems: ["Free progression", "Raid routine"],
    pvpRelevance: "Indirect via roster growth.",
    raidRelevance: "Core free raid item.",
    notes: ["Use consistently to avoid losing daily value."],
    searchTags: ["raid pass", "daily", "local raid"]
  },
  {
    id: 17,
    slug: "remote-raid-pass",
    name: "Remote Raid Pass",
    category: "raid",
    categoryLabel: "Raid Passes",
    rarity: "Rare",
    availability: "Premium",
    description: "Remote participation pass for eligible raids.",
    inGameEffect: "Allows joining raids from distance.",
    stackCap: "Limited carry amount",
    consumable: true,
    acquisition: ["Shop", "Bundles", "Special offers"],
    bestUseCases: ["Global boss access", "Off-hour raid invitations"],
    relatedSystems: ["Remote communities", "Global coordination"],
    pvpRelevance: "Indirect.",
    raidRelevance: "Very high flexibility value.",
    notes: ["Best used on high-impact rotations."],
    searchTags: ["remote pass", "distance raid", "premium"]
  },
  {
    id: 18,
    slug: "incense",
    name: "Incense",
    category: "spawn",
    categoryLabel: "Spawn Tools",
    rarity: "Uncommon",
    availability: "Both",
    description: "Personal spawn booster for a timed duration.",
    inGameEffect: "Generates additional nearby encounters.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Shop", "Research", "Events"],
    bestUseCases: ["Low-density zones", "Event windows"],
    relatedSystems: ["Spawn optimization", "Walking sessions"],
    pvpRelevance: "Indirect through candidate volume.",
    raidRelevance: "No direct raid effect.",
    notes: ["Pair with movement and event bonuses for best value."],
    searchTags: ["incense", "spawn boost", "event"]
  },
  {
    id: 19,
    slug: "lucky-egg",
    name: "Lucky Egg",
    category: "boost",
    categoryLabel: "Boosters",
    rarity: "Rare",
    availability: "Both",
    description: "Timed XP multiplier booster.",
    inGameEffect: "Doubles XP for duration.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Shop", "Level rewards", "Events", "Research"],
    bestUseCases: ["Friendship level-ups", "Mass evolution sessions"],
    relatedSystems: ["XP routing", "Account leveling"],
    pvpRelevance: "Indirect only.",
    raidRelevance: "Indirect only.",
    notes: ["Stack with high-XP activities before activation."],
    searchTags: ["lucky egg", "xp", "multiplier"]
  },
  {
    id: 20,
    slug: "star-piece",
    name: "Star Piece",
    category: "boost",
    categoryLabel: "Boosters",
    rarity: "Rare",
    availability: "Both",
    description: "Timed Stardust gain multiplier.",
    inGameEffect: "Boosts Stardust earned during active window.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Shop", "Events", "Research", "Battle rewards"],
    bestUseCases: ["GO Battle League sets", "Catch-heavy events"],
    relatedSystems: ["Dust economy", "PvP build funding"],
    pvpRelevance: "Very high indirect value.",
    raidRelevance: "Medium indirect value.",
    notes: ["Use during peak dust activities for maximum return."],
    searchTags: ["star piece", "stardust", "booster"]
  },
  {
    id: 21,
    slug: "super-incubator",
    name: "Super Incubator",
    category: "incubator",
    categoryLabel: "Eggs",
    rarity: "Rare",
    availability: "Premium",
    description: "Faster egg hatching incubator with limited uses.",
    inGameEffect: "Reduces distance needed to hatch eggs.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Shop", "Bundles", "Event rewards"],
    bestUseCases: ["10 km / 12 km egg cycles", "Hatch events"],
    relatedSystems: ["Walking efficiency", "Egg strategy"],
    pvpRelevance: "Indirect through hatch-exclusive species.",
    raidRelevance: "No direct effect.",
    notes: ["Prioritize long-distance eggs for best efficiency."],
    searchTags: ["super incubator", "egg", "distance"]
  },
  {
    id: 22,
    slug: "rocket-radar",
    name: "Rocket Radar",
    category: "utility",
    categoryLabel: "Utility",
    rarity: "Uncommon",
    availability: "Both",
    description: "Leader tracker for Team GO Rocket encounters.",
    inGameEffect: "Reveals leader locations for battle.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Mysterious Components", "Shop bundles"],
    bestUseCases: ["Leader farming", "Shadow target hunting"],
    relatedSystems: ["Rocket loop", "Shadow roster growth"],
    pvpRelevance: "Indirect through shadow access.",
    raidRelevance: "Indirect through shadow raid attackers.",
    notes: ["Save for leader rotations with high-value shadows."],
    searchTags: ["rocket radar", "leader", "shadow"]
  },
  {
    id: 23,
    slug: "super-rocket-radar",
    name: "Super Rocket Radar",
    category: "utility",
    categoryLabel: "Utility",
    rarity: "Epic",
    availability: "Event",
    description: "Special radar for Giovanni encounters.",
    inGameEffect: "Tracks Giovanni and decoy encounters.",
    stackCap: "Very limited",
    consumable: true,
    acquisition: ["Special research lines"],
    bestUseCases: ["Shadow legendary targeting windows"],
    relatedSystems: ["Giovanni arc", "Shadow legendary planning"],
    pvpRelevance: "High indirect potential.",
    raidRelevance: "High indirect potential.",
    notes: ["Use strategically by reward rotation."],
    searchTags: ["super radar", "giovanni", "shadow legendary"]
  },
  {
    id: 24,
    slug: "rare-candy",
    name: "Rare Candy",
    category: "special",
    categoryLabel: "Special Access",
    rarity: "Rare",
    availability: "Both",
    description: "Universal candy that converts into any species candy.",
    inGameEffect: "Player chooses species for conversion.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Raids", "GO Battle League", "Research"],
    bestUseCases: ["Legendary/mythical progression", "Critical evolution pushes"],
    relatedSystems: ["Candy economy", "Master League prep"],
    pvpRelevance: "High for expensive builds.",
    raidRelevance: "High for hard-to-farm raid attackers.",
    notes: ["Spend on species with poor farming access."],
    searchTags: ["rare candy", "universal", "legendary"]
  },
  {
    id: 25,
    slug: "super-potion",
    name: "Super Potion",
    category: "healing",
    categoryLabel: "Healing",
    rarity: "Common",
    availability: "Both",
    description: "Mid-tier healing item for early and mid-game battles.",
    inGameEffect: "Restores moderate HP.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Gyms", "Gifts"],
    bestUseCases: ["Rocket battles", "General gym maintenance"],
    relatedSystems: ["Battle sustain"],
    pvpRelevance: "No direct use in league matches.",
    raidRelevance: "Useful for light raid recovery.",
    notes: ["Keep some, recycle excess at high level."],
    searchTags: ["super potion", "healing", "recover"]
  },
  {
    id: 26,
    slug: "max-potion",
    name: "Max Potion",
    category: "healing",
    categoryLabel: "Healing",
    rarity: "Rare",
    availability: "Both",
    description: "Top healing potion for fast full HP recovery.",
    inGameEffect: "Restores full HP.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Raids", "Research", "Events", "Gifts"],
    bestUseCases: ["High-volume raid sessions", "Shadow raids"],
    relatedSystems: ["Raid speed", "Battle loop"],
    pvpRelevance: "No direct use in league matches.",
    raidRelevance: "High for repeated relobbies.",
    notes: ["Prioritize over low-tier potions when bag is tight."],
    searchTags: ["max potion", "full heal", "raids"]
  },
  {
    id: 27,
    slug: "revive",
    name: "Revive",
    category: "healing",
    categoryLabel: "Healing",
    rarity: "Uncommon",
    availability: "Both",
    description: "Brings back a fainted Pokemon with partial HP.",
    inGameEffect: "Revives a fainted Pokemon.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Gyms", "Raids", "Research", "Gifts"],
    bestUseCases: ["Gym clears", "Rocket sessions", "Raid relobby"],
    relatedSystems: ["Battle sustain", "Roster uptime"],
    pvpRelevance: "No direct use in league matches.",
    raidRelevance: "Essential for repeat raiding.",
    notes: ["Pair with potions for full recovery flow."],
    searchTags: ["revive", "fainted", "recovery"]
  },
  {
    id: 28,
    slug: "elite-fast-tm",
    name: "Elite Fast TM",
    category: "battle",
    categoryLabel: "Battle Tech",
    rarity: "Epic",
    availability: "Premium",
    description: "Lets you choose a specific fast move, including legacy.",
    inGameEffect: "Directly selects eligible fast attack.",
    stackCap: "Limited",
    consumable: true,
    acquisition: ["Premium tracks", "Seasonal rewards", "Special bundles"],
    bestUseCases: ["Legacy build unlocks", "Meta move corrections"],
    relatedSystems: ["PvP optimization", "Raid DPS tuning"],
    pvpRelevance: "Extremely high on select species.",
    raidRelevance: "High when best move is legacy.",
    notes: ["Spend only on long-term core Pokemon."],
    searchTags: ["elite fast tm", "legacy", "meta"]
  },
  {
    id: 29,
    slug: "kings-rock",
    name: "King's Rock",
    category: "evolution",
    categoryLabel: "Evolution Items",
    rarity: "Rare",
    availability: "Both",
    description: "Evolution stone required by select species.",
    inGameEffect: "Enables specific item-gated evolutions.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Research breakthroughs", "Events"],
    bestUseCases: ["Dex completion", "Targeted evolution projects"],
    relatedSystems: ["Evolution pipeline"],
    pvpRelevance: "Medium indirect value.",
    raidRelevance: "Low to medium by species.",
    notes: ["Keep a reserve for future evolution events."],
    searchTags: ["kings rock", "evolution item", "johto"]
  },
  {
    id: 30,
    slug: "metal-coat",
    name: "Metal Coat",
    category: "evolution",
    categoryLabel: "Evolution Items",
    rarity: "Rare",
    availability: "Both",
    description: "Required evolution item for metallic species lines.",
    inGameEffect: "Unlocks item-specific evolutions.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Research", "Events"],
    bestUseCases: ["Steel line progression", "Meta prep"],
    relatedSystems: ["Evolution planning", "Type coverage"],
    pvpRelevance: "Medium indirect value.",
    raidRelevance: "Medium indirect value.",
    notes: ["Useful during themed steel events."],
    searchTags: ["metal coat", "steel", "evolution"]
  },
  {
    id: 31,
    slug: "dragon-scale",
    name: "Dragon Scale",
    category: "evolution",
    categoryLabel: "Evolution Items",
    rarity: "Rare",
    availability: "Both",
    description: "Evolution item tied to dragon-related lines.",
    inGameEffect: "Required for specific item-gated evolution.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Research", "Events"],
    bestUseCases: ["Dex lines requiring dragon-scale evolution"],
    relatedSystems: ["Evolution goals"],
    pvpRelevance: "Species dependent.",
    raidRelevance: "Species dependent.",
    notes: ["Drop rate can vary by season and events."],
    searchTags: ["dragon scale", "evolution", "item"]
  },
  {
    id: 32,
    slug: "sun-stone",
    name: "Sun Stone",
    category: "evolution",
    categoryLabel: "Evolution Items",
    rarity: "Rare",
    availability: "Both",
    description: "Evolution item for selected grass and sun-themed lines.",
    inGameEffect: "Enables species-specific evolutions.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Research", "Events"],
    bestUseCases: ["Dex completion", "Limited-time line evolutions"],
    relatedSystems: ["Evolution planning"],
    pvpRelevance: "Species dependent.",
    raidRelevance: "Species dependent.",
    notes: ["Keep extra copies for event windows."],
    searchTags: ["sun stone", "evolution", "grass"]
  },
  {
    id: 33,
    slug: "up-grade",
    name: "Up-Grade",
    category: "evolution",
    categoryLabel: "Evolution Items",
    rarity: "Rare",
    availability: "Both",
    description: "Device-like evolution item for technology lines.",
    inGameEffect: "Unlocks item-required evolution paths.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Research", "Events"],
    bestUseCases: ["Dex progression for tech species"],
    relatedSystems: ["Evolution goals", "Collection completions"],
    pvpRelevance: "Species dependent.",
    raidRelevance: "Low to medium by species.",
    notes: ["Do not discard if you still need line completion."],
    searchTags: ["up-grade", "upgrade", "evolution item"]
  },
  {
    id: 34,
    slug: "mossy-lure-module",
    name: "Mossy Lure Module",
    category: "spawn",
    categoryLabel: "Spawn Tools",
    rarity: "Rare",
    availability: "Premium",
    description: "Lure variant that attracts specific species and supports evolutions.",
    inGameEffect: "Modifies nearby spawns and enables special evolutions.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Shop", "Bundles", "Research rewards"],
    bestUseCases: ["Targeted grass/bug farming", "Evolution requirements"],
    relatedSystems: ["Spawn manipulation", "Evolution unlocks"],
    pvpRelevance: "Indirect through targeted catches.",
    raidRelevance: "Indirect only.",
    notes: ["Best used in active lure clusters."],
    searchTags: ["mossy lure", "lure", "spawn control"]
  },
  {
    id: 35,
    slug: "glacial-lure-module",
    name: "Glacial Lure Module",
    category: "spawn",
    categoryLabel: "Spawn Tools",
    rarity: "Rare",
    availability: "Premium",
    description: "Lure module for ice/water-biased spawn patterns.",
    inGameEffect: "Adds themed spawns and evolution utility.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Shop", "Bundles", "Events"],
    bestUseCases: ["Seasonal ice projects", "Evolution targets"],
    relatedSystems: ["Spawn curation", "Dex progress"],
    pvpRelevance: "Indirect through species access.",
    raidRelevance: "Indirect only.",
    notes: ["Coordinate with weather boosts for better returns."],
    searchTags: ["glacial lure", "ice spawn", "evolution"]
  },
  {
    id: 36,
    slug: "magnetic-lure-module",
    name: "Magnetic Lure Module",
    category: "spawn",
    categoryLabel: "Spawn Tools",
    rarity: "Rare",
    availability: "Premium",
    description: "Lure module focused on electric and steel ecosystems.",
    inGameEffect: "Changes local spawn table and supports special evolutions.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Shop", "Bundles", "Event rewards"],
    bestUseCases: ["Steel/electric projects", "Line-specific evolutions"],
    relatedSystems: ["Spawn targeting", "Evolution access"],
    pvpRelevance: "Indirect via targeted species farming.",
    raidRelevance: "Indirect only.",
    notes: ["Use in crowded Pokestop zones for maximum value."],
    searchTags: ["magnetic lure", "electric", "steel"]
  },
  {
    id: 37,
    slug: "rainy-lure-module",
    name: "Rainy Lure Module",
    category: "spawn",
    categoryLabel: "Spawn Tools",
    rarity: "Rare",
    availability: "Premium",
    description: "Lure module that boosts water/bug/electric style encounters.",
    inGameEffect: "Spawns themed encounters around a Pokestop.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Shop", "Bundles", "Seasonal research"],
    bestUseCases: ["Water event optimization", "Rain-themed line hunts"],
    relatedSystems: ["Spawn optimization", "Dex hunting"],
    pvpRelevance: "Indirect by expanding candidate catches.",
    raidRelevance: "Indirect only.",
    notes: ["Good for wet-weather event synergy."],
    searchTags: ["rainy lure", "water", "spawn"]
  },
  {
    id: 38,
    slug: "golden-lure-module",
    name: "Golden Lure Module",
    category: "spawn",
    categoryLabel: "Spawn Tools",
    rarity: "Epic",
    availability: "Event",
    description: "Special lure tied to coin-focused interactions and rare spawns.",
    inGameEffect: "Upgrades stop interactions during active lure window.",
    stackCap: "Limited",
    consumable: true,
    acquisition: ["System milestones", "Limited events"],
    bestUseCases: ["Coin farming windows", "Golden-stop coordination"],
    relatedSystems: ["Economy", "Event loops"],
    pvpRelevance: "Indirect only.",
    raidRelevance: "Indirect only.",
    notes: ["Coordinate with nearby players for best value."],
    searchTags: ["golden lure", "coins", "event lure"]
  },
  {
    id: 39,
    slug: "premium-battle-pass",
    name: "Premium Battle Pass",
    category: "raid",
    categoryLabel: "Raid Passes",
    rarity: "Rare",
    availability: "Premium",
    description: "Paid pass used for local raids and premium battle entry.",
    inGameEffect: "Provides raid access and premium battle track entry.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Shop", "Bundles", "Special packs"],
    bestUseCases: ["Extra raid volume", "Premium reward tracks"],
    relatedSystems: ["Raid economy", "Battle progression"],
    pvpRelevance: "Indirect via rewards and resources.",
    raidRelevance: "High for planned rotations.",
    notes: ["Use during top boss rotations."],
    searchTags: ["premium pass", "raid pass", "paid raid"]
  },
  {
    id: 40,
    slug: "poffin",
    name: "Poffin",
    category: "boost",
    categoryLabel: "Boosters",
    rarity: "Rare",
    availability: "Premium",
    description: "Buddy boost snack that accelerates buddy progress.",
    inGameEffect: "Instantly increases buddy mood and bonus windows.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Shop", "Event rewards", "Research"],
    bestUseCases: ["XL grind routes", "Buddy heart optimization"],
    relatedSystems: ["Buddy system", "Candy XL farming"],
    pvpRelevance: "Indirect through buddy-candy pipelines.",
    raidRelevance: "Indirect through faster project progression.",
    notes: ["Best saved for high-priority buddies."],
    searchTags: ["poffin", "buddy", "hearts"]
  },
  {
    id: 41,
    slug: "rare-candy-xl",
    name: "Rare Candy XL",
    category: "special",
    categoryLabel: "Special Access",
    rarity: "Epic",
    availability: "Both",
    description: "High-value candy resource for level 40+ progression.",
    inGameEffect: "Converts into species-specific XL candy.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Raids", "GO Battle League", "High-tier research"],
    bestUseCases: ["Master League legendaries", "Level 50 projects"],
    relatedSystems: ["XL economy", "Endgame builds"],
    pvpRelevance: "Very high for ML meta progression.",
    raidRelevance: "High for maxed raid attackers.",
    notes: ["Use on species with poor XL availability."],
    searchTags: ["rare candy xl", "xl", "level 50"]
  },
  {
    id: 42,
    slug: "nanab-berry",
    name: "Nanab Berry",
    category: "berries",
    categoryLabel: "Berries",
    rarity: "Common",
    availability: "Both",
    description: "Berry that calms target movement during encounters.",
    inGameEffect: "Reduces target movement/attack frequency.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Pokestops", "Gyms", "Gifts", "Research"],
    bestUseCases: ["Tricky movement catches", "Task requirements"],
    relatedSystems: ["Catch consistency"],
    pvpRelevance: "Indirect only.",
    raidRelevance: "Usually niche for raid catch phase.",
    notes: ["Situational but useful on jumpy targets."],
    searchTags: ["nanab", "berry", "calm movement"]
  },
  {
    id: 43,
    slug: "silver-pinap-berry",
    name: "Silver Pinap Berry",
    category: "berries",
    categoryLabel: "Berries",
    rarity: "Rare",
    availability: "Event",
    description: "Hybrid berry with candy and catch-rate benefits.",
    inGameEffect: "Boosts both candy yield and catch performance.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Special research", "Event rewards"],
    bestUseCases: ["Rare catches where candy and security both matter"],
    relatedSystems: ["Candy routing", "Catch optimization"],
    pvpRelevance: "High indirect value on rare species.",
    raidRelevance: "Situational high value.",
    notes: ["Excellent premium berry for high-value targets."],
    searchTags: ["silver pinap", "berry", "candy bonus"]
  },
  {
    id: 44,
    slug: "premier-ball",
    name: "Premier Ball",
    category: "balls",
    categoryLabel: "Capture Balls",
    rarity: "Rare",
    availability: "Event",
    description: "Special ball used in raid and event capture phases.",
    inGameEffect: "Event-limited capture ball allocation.",
    stackCap: "Session-bound",
    consumable: true,
    acquisition: ["Raid completion", "Event encounters"],
    bestUseCases: ["Raid boss capture windows"],
    relatedSystems: ["Raid capture"],
    pvpRelevance: "Indirect through secured catches.",
    raidRelevance: "Core to raid captures.",
    notes: ["Curve + timing discipline remains crucial."],
    searchTags: ["premier ball", "raid catch", "event ball"]
  },
  {
    id: 45,
    slug: "beast-ball",
    name: "Beast Ball",
    category: "balls",
    categoryLabel: "Capture Balls",
    rarity: "Epic",
    availability: "Event",
    description: "Specialized event ball associated with Ultra Beast windows.",
    inGameEffect: "Custom catch behavior during limited events.",
    stackCap: "Event-bound",
    consumable: true,
    acquisition: ["Limited raid/event encounters"],
    bestUseCases: ["Ultra Beast event catches"],
    relatedSystems: ["Event capture systems"],
    pvpRelevance: "Indirect only.",
    raidRelevance: "Niche, event-dependent.",
    notes: ["Availability depends on active event rules."],
    searchTags: ["beast ball", "ultra beast", "event"]
  },
  {
    id: 46,
    slug: "daily-adventure-incense",
    name: "Daily Adventure Incense",
    category: "spawn",
    categoryLabel: "Spawn Tools",
    rarity: "Rare",
    availability: "Free",
    description: "Daily limited incense with unique spawn pool behavior.",
    inGameEffect: "Generates special timed encounters while moving.",
    stackCap: "Daily charge",
    consumable: true,
    acquisition: ["Daily free availability"],
    bestUseCases: ["Daily rare spawn checks", "Walking sessions"],
    relatedSystems: ["Daily routine", "Rare encounters"],
    pvpRelevance: "Indirect through rare species access.",
    raidRelevance: "No direct raid impact.",
    notes: ["Movement and active play improve value."],
    searchTags: ["daily incense", "adventure incense", "rare spawn"]
  },
  {
    id: 47,
    slug: "incubator",
    name: "Incubator",
    category: "incubator",
    categoryLabel: "Eggs",
    rarity: "Rare",
    availability: "Premium",
    description: "Standard multi-use incubator for egg hatching.",
    inGameEffect: "Allows hatching eggs over distance.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Shop", "Bundles", "Timed research"],
    bestUseCases: ["Batch hatch projects", "Event egg pools"],
    relatedSystems: ["Egg strategy", "Walking loop"],
    pvpRelevance: "Indirect via hatch-exclusive species.",
    raidRelevance: "No direct effect.",
    notes: ["Use on medium/long distance eggs for efficiency."],
    searchTags: ["incubator", "hatch eggs", "walking"]
  },
  {
    id: 48,
    slug: "egg-incubator",
    name: "Egg Incubator",
    category: "incubator",
    categoryLabel: "Eggs",
    rarity: "Common",
    availability: "Free",
    description: "Permanent core incubator available to every trainer.",
    inGameEffect: "Infinite basic egg hatching slot.",
    stackCap: "1 permanent",
    consumable: false,
    acquisition: ["Base trainer equipment"],
    bestUseCases: ["Always-on hatch progression"],
    relatedSystems: ["Core egg gameplay"],
    pvpRelevance: "Indirect only.",
    raidRelevance: "No direct effect.",
    notes: ["Prioritize longest eggs in premium incubators first."],
    searchTags: ["egg incubator", "infinite incubator", "free hatch"]
  },
  {
    id: 49,
    slug: "mysterious-component",
    name: "Mysterious Component",
    category: "utility",
    categoryLabel: "Utility",
    rarity: "Common",
    availability: "Free",
    description: "Rocket part collected to assemble a Rocket Radar.",
    inGameEffect: "Six components craft one Rocket Radar.",
    stackCap: "Limited while radar is active",
    consumable: true,
    acquisition: ["Team GO Rocket Grunt battles"],
    bestUseCases: ["Leader unlock cycle", "Shadow target farming"],
    relatedSystems: ["Rocket progression"],
    pvpRelevance: "Indirect via shadow species access.",
    raidRelevance: "Indirect only.",
    notes: ["Components stop dropping when radar is equipped."],
    searchTags: ["mysterious component", "rocket", "radar craft"]
  },
  {
    id: 50,
    slug: "mystery-box",
    name: "Mystery Box",
    category: "utility",
    categoryLabel: "Utility",
    rarity: "Rare",
    availability: "Both",
    description: "Special box that enables timed mythical spawn sessions.",
    inGameEffect: "Activates a unique species spawn window.",
    stackCap: "Single reusable item",
    consumable: false,
    acquisition: ["External game integration"],
    bestUseCases: ["Mythical species farming", "Shiny hunting windows"],
    relatedSystems: ["Cross-game systems", "Special encounters"],
    pvpRelevance: "Species dependent.",
    raidRelevance: "No direct effect.",
    notes: ["Cooldown applies between activations."],
    searchTags: ["mystery box", "special spawn", "mythical"]
  },
  {
    id: 51,
    slug: "coin-bag",
    name: "Coin Bag",
    category: "utility",
    categoryLabel: "Utility",
    rarity: "Rare",
    availability: "Both",
    description: "Reusable utility item tied to coin-focused special spawns.",
    inGameEffect: "Triggers specific encounter windows after refresh steps.",
    stackCap: "Single reusable item",
    consumable: false,
    acquisition: ["External game integration"],
    bestUseCases: ["Special species farming", "Coin event synergy"],
    relatedSystems: ["Special encounters", "Economy loops"],
    pvpRelevance: "Indirect only.",
    raidRelevance: "No direct effect.",
    notes: ["Activation depends on external refresh requirements."],
    searchTags: ["coin bag", "special spawn", "integration"]
  },
  {
    id: 52,
    slug: "gift",
    name: "Gift",
    category: "utility",
    categoryLabel: "Utility",
    rarity: "Common",
    availability: "Free",
    description: "Social package sent to friends with mixed rewards.",
    inGameEffect: "Provides items, stickers, and chance-based extras.",
    stackCap: "Daily send/open limits",
    consumable: true,
    acquisition: ["Pokestops", "Buddy gifts"],
    bestUseCases: ["Item sustain", "Friendship XP growth"],
    relatedSystems: ["Social loop", "XP routing"],
    pvpRelevance: "Indirect via resource income.",
    raidRelevance: "Indirect via item sustain.",
    notes: ["Coordinate opens with Lucky Egg for XP spikes."],
    searchTags: ["gift", "friends", "friendship xp"]
  },
  {
    id: 53,
    slug: "sticker",
    name: "Sticker",
    category: "utility",
    categoryLabel: "Utility",
    rarity: "Common",
    availability: "Both",
    description: "Cosmetic social item attached to gifts.",
    inGameEffect: "No gameplay stats; social personalization.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Gifts", "Shop", "Event rewards"],
    bestUseCases: ["Gift personalization", "Collection flavor"],
    relatedSystems: ["Social interactions"],
    pvpRelevance: "None.",
    raidRelevance: "None.",
    notes: ["Purely cosmetic."],
    searchTags: ["sticker", "cosmetic", "gift"]
  },
  {
    id: 54,
    slug: "xl-candy",
    name: "XL Candy",
    category: "special",
    categoryLabel: "Special Access",
    rarity: "Rare",
    availability: "Both",
    description: "Species-specific endgame candy for high-level power-ups.",
    inGameEffect: "Used beyond level 40 for Pokemon leveling.",
    stackCap: "999+",
    consumable: true,
    acquisition: ["Catches", "Transfers", "Trades", "Raids", "Walking buddy"],
    bestUseCases: ["Level 50 PvP builds", "Maxed raid attackers"],
    relatedSystems: ["Endgame power progression"],
    pvpRelevance: "Very high.",
    raidRelevance: "Very high.",
    notes: ["Plan XL spending around high-priority projects."],
    searchTags: ["xl candy", "level 50", "power up"]
  },
  {
    id: 55,
    slug: "team-medallion",
    name: "Team Medallion",
    category: "special",
    categoryLabel: "Special Access",
    rarity: "Epic",
    availability: "Premium",
    description: "Premium token used to switch trainer team.",
    inGameEffect: "Changes team alignment after cooldown constraints.",
    stackCap: "Inventory-based",
    consumable: true,
    acquisition: ["Shop"],
    bestUseCases: ["Team migration for local community strategy"],
    relatedSystems: ["Gym control", "Social coordination"],
    pvpRelevance: "Indirect only.",
    raidRelevance: "Indirect only.",
    notes: ["Team swap has cooldown and strategic impact."],
    searchTags: ["team medallion", "team change", "premium"]
  },
  {
    id: 56,
    slug: "poke-coin",
    name: "Poke Coin",
    category: "special",
    categoryLabel: "Special Access",
    rarity: "Rare",
    availability: "Both",
    description: "Core premium currency for shop purchases.",
    inGameEffect: "Used to buy passes, bundles, and upgrades.",
    stackCap: "Account wallet",
    consumable: true,
    acquisition: ["Gym defense rewards", "In-app purchases"],
    bestUseCases: ["Raid item budgeting", "Storage upgrades"],
    relatedSystems: ["Economy", "Resource planning"],
    pvpRelevance: "Indirect through build resources.",
    raidRelevance: "Indirect through pass access.",
    notes: ["Prioritize permanent value purchases first."],
    searchTags: ["poke coin", "currency", "shop"]
  },
  {
    id: 57,
    slug: "item-bag-upgrade",
    name: "Item Bag Upgrade",
    category: "special",
    categoryLabel: "Special Access",
    rarity: "Rare",
    availability: "Premium",
    description: "Permanent increase to item bag storage.",
    inGameEffect: "Raises max item inventory capacity.",
    stackCap: "Account progression",
    consumable: true,
    acquisition: ["Shop"],
    bestUseCases: ["Long sessions", "Raid and event stockpiles"],
    relatedSystems: ["Inventory management", "Event prep"],
    pvpRelevance: "Indirect via better resource retention.",
    raidRelevance: "Indirect via pass/heal stockpiles.",
    notes: ["One of the highest long-term value purchases."],
    searchTags: ["item bag", "storage", "upgrade"]
  },
  {
    id: 58,
    slug: "pokemon-storage-upgrade",
    name: "Pokemon Storage Upgrade",
    category: "special",
    categoryLabel: "Special Access",
    rarity: "Rare",
    availability: "Premium",
    description: "Permanent expansion for Pokemon collection slots.",
    inGameEffect: "Increases Pokemon storage cap.",
    stackCap: "Account progression",
    consumable: true,
    acquisition: ["Shop"],
    bestUseCases: ["Collection-heavy players", "Event catch marathons"],
    relatedSystems: ["Collection management", "Trade prep"],
    pvpRelevance: "High indirect value for roster depth.",
    raidRelevance: "Medium indirect value.",
    notes: ["Strong long-term account investment."],
    searchTags: ["pokemon storage", "box space", "upgrade"]
  },
  {
    id: 59,
    slug: "postcard-book",
    name: "Postcard Book",
    category: "utility",
    categoryLabel: "Utility",
    rarity: "Uncommon",
    availability: "Both",
    description: "Travel/social archive feature for saved gift postcards.",
    inGameEffect: "Stores and tracks postcard interactions.",
    stackCap: "Feature capacity",
    consumable: false,
    acquisition: ["Core feature unlock"],
    bestUseCases: ["Vivillon progression tracking", "Travel collection logs"],
    relatedSystems: ["Social", "Collection goals"],
    pvpRelevance: "Indirect only.",
    raidRelevance: "None.",
    notes: ["Supports long-term collection objectives."],
    searchTags: ["postcard", "vivillon", "gift collection"]
  },
  {
    id: 60,
    slug: "mega-energy",
    name: "Mega Energy",
    category: "special",
    categoryLabel: "Special Access",
    rarity: "Rare",
    availability: "Both",
    description: "Species-tied resource used for mega evolution cycles.",
    inGameEffect: "Enables and sustains mega evolution activations.",
    stackCap: "Species-specific pool",
    consumable: true,
    acquisition: ["Mega raids", "Research", "Event tasks", "Buddy walking"],
    bestUseCases: ["Raid damage boosts", "Type-specific event bonuses"],
    relatedSystems: ["Mega system", "Raid optimization"],
    pvpRelevance: "Limited but growing by format.",
    raidRelevance: "High for teamwide DPS bonuses.",
    notes: ["Prioritize mega lines with broad raid utility."],
    searchTags: ["mega energy", "mega evolution", "raid boost"]
  }
];

const completeItems = completePokemonGoItems as PokemonGoItem[];
const curatedBySlug = new Map(CURATED_POKEMON_GO_ITEMS.map((item) => [item.slug, item]));

const mergedCompleteItems = completeItems.map((item) => {
  const curatedItem = curatedBySlug.get(item.slug);
  if (!curatedItem) {
    return item;
  }

  return {
    ...item,
    ...curatedItem,
    id: curatedItem.id
  };
});

const mergedBySlug = new Map(mergedCompleteItems.map((item) => [item.slug, item]));
for (const curatedItem of CURATED_POKEMON_GO_ITEMS) {
  if (!mergedBySlug.has(curatedItem.slug)) {
    mergedBySlug.set(curatedItem.slug, curatedItem);
  }
}

export const POKEMON_GO_ITEMS: PokemonGoItem[] = Array.from(mergedBySlug.values()).sort((a, b) =>
  a.name.localeCompare(b.name)
);

const POKEMON_GO_ITEM_SEARCH_INDEX = POKEMON_GO_ITEMS.map((item) => ({
  item,
  haystack: [
    item.name,
    item.categoryLabel,
    item.rarity,
    item.availability,
    item.description,
    item.inGameEffect,
    item.stackCap,
    item.pvpRelevance,
    item.raidRelevance,
    ...item.acquisition,
    ...item.bestUseCases,
    ...item.relatedSystems,
    ...item.notes,
    ...item.searchTags
  ]
    .map(normalize)
    .join(" ")
}));
const POKEMON_GO_ITEM_BY_ID = new Map(POKEMON_GO_ITEMS.map((item) => [item.id, item]));

export function searchPokemonGoItems(query: string) {
  const normalizedQuery = normalize(query);
  if (!normalizedQuery) {
    return POKEMON_GO_ITEMS;
  }

  return POKEMON_GO_ITEM_SEARCH_INDEX.filter((entry) =>
    entry.haystack.includes(normalizedQuery)
  ).map((entry) => entry.item);
}

export function getPokemonGoItemById(itemId: number | null) {
  if (itemId === null) {
    return null;
  }
  return POKEMON_GO_ITEM_BY_ID.get(itemId) ?? null;
}

export function getPokemonGoItemCategoryOptions() {
  const map = new Map<PokemonGoItemCategory, string>();
  for (const entry of POKEMON_GO_ITEMS) {
    if (!map.has(entry.category)) {
      map.set(entry.category, entry.categoryLabel);
    }
  }
  return Array.from(map.entries()).map(([value, label]) => ({ value, label }));
}
